Config = {}

Config.Healing = 1 -- // If this is 0, then its disabled.. Default: 3.. That means, if a person lies in a bed, then he will get 1 health every 3 seconds.
Config.Cooldown = 0 -- // If this is 0, then its disabled.. Default: 2.. That means, if a player goes and stand up, then he need to wait 2 seconds, before he can lay/sit again! [VERY RECOMMENDED]

Config.objects = {
	Object = nil, ObjectVertX = nil, ObjectVertY = nil, ObjectVertZ = nil, ObjectDir = nil, isBed = nil, -- // Please don't change this line!;)
	ButtonToSitOnChair = 38, -- // Default: G -- // https://docs.fivem.net/game-references/controls/
	ButtonToLayOnBed = 38, -- // Default: E -- // https://docs.fivem.net/game-references/controls/
	ButtonToStandUp = 23, -- // Default: F -- // https://docs.fivem.net/game-references/controls/
	SitAnimation = {anim='PROP_HUMAN_SEAT_CHAIR_MP_PLAYER'},
	BedBackAnimation = {dict='"missarmenian2"', anim='corpse_search_exit_ped'},
	BedStomachAnimation = {dict='missarmenian2', anim='drunk_loop'},
	BedSitAnimation = {anim='WORLD_HUMAN_PICNIC'},
	locations = {
		[1] = {object="bkr_prop_biker_campbed_01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=0.0, direction=0.0, bed=true, tent=false},
		[2] = {object="v_serv_ct_chair02", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.0, direction=180.0, bed=false, tent=false},
		[3] = {object="prop_off_chair_04", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=180.0, bed=false, tent=false},
		[4] = {object="prop_off_chair_03", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=180.0, bed=false, tent=false},
		[5] = {object="prop_off_chair_05", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=180.0, bed=false, tent=false},
		[6] = {object="v_club_officechair", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.53, direction=180.0, bed=false, tent=false},
		[7] = {object="v_ilev_leath_chr", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=180.0, bed=false, tent=false},
		[8] = {object="v_corp_offchair", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.4, direction=180.0, bed=false, tent=false},
		[9] = {object="bkr_prop_clubhouse_offchair_01a", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=0.0, direction=180.0, bed=false, tent=false},
		[10] = {object="Prop_Off_Chair_01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[11] = {object="prop_bench_01a", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[12] = {object="prop_bench_01b", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[13] = {object="prop_bench_01c", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[14] = {object="prop_bench_02", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[15] = {object="prop_bench_03", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[16] = {object="prop_bench_04", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[17] = {object="prop_bench_05", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[18] = {object="prop_bench_06", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[19] = {object="prop_bench_08", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[20] = {object="prop_bench_09", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[21] = {object="prop_bench_10", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[22] = {object="prop_bench_11", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[23] = {object="prop_fib_3b_bench", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[24] = {object="prop_ld_bench01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[25] = {object="prop_wait_bench_01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[26] = {object="hei_prop_heist_off_chair", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[27] = {object="hei_prop_hei_skid_chair", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[28] = {object="prop_chair_01a", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[29] = {object="prop_chair_01b", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[30] = {object="prop_chair_02", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[31] = {object="prop_chair_03", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[32] = {object="prop_chair_04a", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[33] = {object="prop_chair_04b", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[34] = {object="prop_chair_05", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[35] = {object="prop_chair_06", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[36] = {object="prop_chair_08", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.0, direction=180.0, bed=false, tent=false},
		[37] = {object="prop_chair_09", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[38] = {object="prop_chair_10", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[39] = {object="prop_chateau_chair_01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[40] = {object="prop_clown_chair", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[41] = {object="prop_cs_office_chair", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[42] = {object="prop_direct_chair_01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[43] = {object="prop_direct_chair_02", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[44] = {object="prop_gc_chair02", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[45] = {object="prop_off_chair_01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[46] = {object="prop_off_chair_03", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[47] = {object="prop_off_chair_04", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[48] = {object="prop_off_chair_04b", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[49] = {object="prop_off_chair_04_s", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[50] = {object="prop_off_chair_05", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[51] = {object="prop_old_deck_chair", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[52] = {object="prop_old_wood_chair", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[53] = {object="prop_rock_chair_01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[54] = {object="prop_skid_chair_01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.1, direction=180.0, bed=false, tent=false},
		[55] = {object="prop_skid_chair_02", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.1, direction=180.0, bed=false, tent=false},
		[56] = {object="prop_skid_chair_03", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.1, direction=180.0, bed=false, tent=false},
		[57] = {object="prop_sol_chair", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[58] = {object="prop_wheelchair_01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[59] = {object="prop_wheelchair_01_s", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[60] = {object="p_armchair_01_s", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[61] = {object="p_clb_officechair_s", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[62] = {object="p_dinechair_01_s", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[63] = {object="p_ilev_p_easychair_s", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[64] = {object="p_soloffchair_s", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[65] = {object="p_yacht_chair_01_s", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[66] = {object="v_club_officechair", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.0, direction=180.0, bed=false, tent=false},
		[67] = {object="v_corp_bk_chair3", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[68] = {object="v_corp_cd_chair", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[69] = {object="v_corp_offchair", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[70] = {object="v_ilev_chair02_ped", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[71] = {object="v_ilev_p_easychair", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[72] = {object="v_ret_gc_chair03", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=0.1, direction=180.0, bed=false, tent=false},
		[73] = {object="prop_ld_farm_chair01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[74] = {object="prop_table_04_chr", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[75] = {object="prop_table_05_chr", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[76] = {object="prop_table_06_chr", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[77] = {object="v_ilev_leath_chr", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[78] = {object="prop_table_01_chr_a", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[79] = {object="prop_table_01_chr_b", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.01, direction=270.0, bed=false, tent=false},
		[80] = {object="prop_table_02_chr", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[81] = {object="prop_table_03b_chr", verticalOffsetX=0.06, verticalOffsetY=0.05, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[82] = {object="prop_table_03_chr", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[83] = {object="prop_torture_ch_01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.1, direction=180.0, bed=false, tent=false},
		[84] = {object="v_ilev_fh_dineeamesa", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[85] = {object="v_ilev_fh_kitchenstool", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[86] = {object="v_ilev_tort_stool", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[87] = {object="v_ilev_fh_kitchenstool", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[88] = {object="v_ilev_fh_kitchenstool", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[89] = {object="hei_prop_yah_seat_01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[90] = {object="hei_prop_yah_seat_02", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[91] = {object="hei_prop_yah_seat_03", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[92] = {object="prop_waiting_seat_01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[93] = {object="prop_yacht_seat_01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[94] = {object="prop_yacht_seat_02", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[95] = {object="prop_yacht_seat_03", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[96] = {object="prop_hobo_seat_01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[97] = {object="prop_rub_couch01", verticalOffsetX=-0.0, verticalOffsetY=0.1, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[98] = {object="miss_rub_couch_01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[99] = {object="prop_ld_farm_couch01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[100] = {object="prop_ld_farm_couch02", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[101] = {object="prop_rub_couch03", verticalOffsetX=-0.1, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[102] = {object="prop_rub_couch04", verticalOffsetX=-0.1, verticalOffsetY=0.0, verticalOffsetZ=-0.49, direction=180.0, bed=false, tent=false},
		[103] = {object="p_lev_sofa_s", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[104] = {object="p_res_sofa_l_s", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[105] = {object="p_v_med_p_sofa_s", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[106] = {object="p_yacht_sofa_01_s", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[107] = {object="v_ilev_m_sofa", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[108] = {object="v_res_tre_sofa_s", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[109] = {object="v_tre_sofa_mess_a_s", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[110] = {object="v_tre_sofa_mess_b_s", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[111] = {object="v_tre_sofa_mess_c_s", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[112] = {object="prop_roller_car_01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[113] = {object="prop_roller_car_02", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[114] = {object="v_ilev_ph_bench", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[115] = {object="ex_prop_offchair_exec_04", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[116] = {object="ex_prop_offchair_exec_01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[117] = {object="vw_prop_vw_offchair_02", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[118] = {object="vw_prop_casino_chair_01a", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[119] = {object="vw_prop_casino_track_chair_01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[120] = {object="prop_chair_07", verticalOffsetX=-0.065, verticalOffsetY=0.1, verticalOffsetZ=-0.55, direction=180.0, bed=false, tent=false},
		[121] = {object="prop_table_08_chr", verticalOffsetX=0.0, verticalOffsetY=0.1, verticalOffsetZ=-0.3, direction=180.0, bed=false, tent=false},
		[122] = {object="lr_prop_clubstool_01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.8, direction=180.0, bed=false, tent=false},
		[123] = {object="prop_skid_tent_01b", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=0.0, direction=0.0, bed=false, tent=true},
		[124] = {object="prop_skid_tent_01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=0.0, direction=0.0, bed=false, tent=true},
		[125] = {object="prop_skid_tent_cloth", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=0.0, direction=0.0, bed=false, tent=true},
		[126] = {object="prop_skid_tent_03", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=0.0, direction=0.0, bed=false, tent=true},
		[127] = {object="bkr_prop_clubhouse_chair_03", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.5, direction=180.0, bed=false, tent=false},
		[128] = {object="prop_homeles_shelter_02", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.3, direction=25.0, bed=false, tent=true},
		[129] = {object="prop_homeles_shelter_01", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=-0.3, direction=35.0, bed=false, tent=true},
		[130] = {object="prop_bar_stool_01", verticalOffsetX=0.0, verticalOffsetY=-0.0, verticalOffsetZ=-0.8, direction=180.0, bed=false, tent=false},
		[131] = {object="v_med_emptybed", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=0.5, direction=90.0, bed=true, tent=false},
		[132] = {object="v_med_bed2", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=0.0, direction=90.0, bed=true, tent=false},
		[133] = {object="v_med_bed1", verticalOffsetX=0.0, verticalOffsetY=0.0, verticalOffsetZ=0.0, direction=90.0, bed=true, tent=false},
	}
}

Config.Text = {
	SitOnChair = '~g~[E]~w~ to Sit',
	SitOnTent = '~g~[E]~w~ to Enter Tent',
	SitOnBed = '~g~[E]~w~ to Sit on Bed',
	LieOnBed = '~g~[E]~w~ to laydown on your',
	SwitchBetween = '~w~ Switch between your back, stomach or sitting ~g~ With the arrows [right or left]',
	Standup = '~g~[F]~w~ to standup'
}